document.getElementById("Header").innerHTML = '<div class="top-bar">'
    + '<div class="container top-bar-container">'
    + '<a href="#" class="top-bar__logo"><img src="./resources/images-manga-detail/logo.png" alt=""> </a>'
    + '<div class="top-bar__nav">'
        + '<a href="#" class="active nav-item">Home</a>'
        + '<a href="#" class="nav-item">Last Updates</a>'
        + '<a href="#" class="nav-item">Ranking</a>'
        + '<a href="#" class="nav-item">Browse</a>'
    + '</div>'
    + '<div class="top-bar__right">'
        + '<div class="top-bar__search">'
            + '<input type="text" name="title" class="search-input" placeholder="Search Manga" >'
            + '<a href="#" class="search-btn"><i class="fa-solid fa-magnifying-glass"></i></a>'
        + '</div>'
        + '<a class="top-bar__avatar"><img src="images/top-bar-avatar-img.png" alt=""></a>'
    + '</div>'
+ '</div>'
+ '</div>';